use_default_settings: true

general:
  instance_name: "expressindex-search"

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

server:
  secret_key: "changeme123"
  limiter: false
  image_proxy: true
